---
jobs:
- name: greeting
  public: true
  plan:
  - task: greeting
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: [hello world]
